// The shape of a saved blueprint step. Generated by the Strategy Engine,
// stored as a snapshot, rendered on My Blueprint.
export type BlueprintStep = {
  n: number
  kind: 'action' | 'wait' | 'habit'
  title: string
  why: string
  timing: string
  instId?: number
}

export type SavedBlueprint = {
  id: number
  title: string
  mode: 'build' | 'borderline' | 'ready'
  answers: string
  steps: string
  done: string
  created_at: string
}

export function parseSteps(raw: string): BlueprintStep[] {
  try {
    const s = JSON.parse(raw)
    return Array.isArray(s) ? s : []
  } catch {
    return []
  }
}

export function parseDone(raw: string): number[] {
  try {
    const d = JSON.parse(raw)
    return Array.isArray(d) ? d.filter((n: unknown) => Number.isInteger(n)) as number[] : []
  } catch {
    return []
  }
}
